// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLCSWWnS49sOC2JgHfL_mYcFoWVQZaczg',
    appId: '1:606688449179:web:0864f5d1cc671f819d6c3e',
    messagingSenderId: '606688449179',
    projectId: 'auth-6aabd',
    authDomain: 'auth-6aabd.firebaseapp.com',
    storageBucket: 'auth-6aabd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx0XAhLg1wuNoWAWKuUfLhmLmX_oCJTZI',
    appId: '1:606688449179:android:d896d175397aac609d6c3e',
    messagingSenderId: '606688449179',
    projectId: 'auth-6aabd',
    storageBucket: 'auth-6aabd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBgLMkJQs9POpYYK0TmGIwqkfGpTy41q8',
    appId: '1:606688449179:ios:d91c85f062e189489d6c3e',
    messagingSenderId: '606688449179',
    projectId: 'auth-6aabd',
    storageBucket: 'auth-6aabd.appspot.com',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBgLMkJQs9POpYYK0TmGIwqkfGpTy41q8',
    appId: '1:606688449179:ios:d91c85f062e189489d6c3e',
    messagingSenderId: '606688449179',
    projectId: 'auth-6aabd',
    storageBucket: 'auth-6aabd.appspot.com',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLCSWWnS49sOC2JgHfL_mYcFoWVQZaczg',
    appId: '1:606688449179:web:b865d2c68ee48f7e9d6c3e',
    messagingSenderId: '606688449179',
    projectId: 'auth-6aabd',
    authDomain: 'auth-6aabd.firebaseapp.com',
    storageBucket: 'auth-6aabd.appspot.com',
  );

}