// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBziOe3J_ZcLvRcqBunGyQ-6D4FXT7E1tg',
    appId: '1:632537420527:web:3c42002c669440d86c411a',
    messagingSenderId: '632537420527',
    projectId: 'login-a8323',
    authDomain: 'login-a8323.firebaseapp.com',
    databaseURL: 'https://login-a8323-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'login-a8323.appspot.com',
    measurementId: 'G-N9RQC2DH5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX12tDnQwUKdQgvwIPQgJuhBfCEVcjQDQ',
    appId: '1:632537420527:android:289c587365d72da56c411a',
    messagingSenderId: '632537420527',
    projectId: 'login-a8323',
    databaseURL: 'https://login-a8323-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'login-a8323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOZ2z9oNw6e-meHr6GkmXiA-Mq3pn351A',
    appId: '1:632537420527:ios:55e4b9362b15d4806c411a',
    messagingSenderId: '632537420527',
    projectId: 'login-a8323',
    databaseURL: 'https://login-a8323-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'login-a8323.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOZ2z9oNw6e-meHr6GkmXiA-Mq3pn351A',
    appId: '1:632537420527:ios:55e4b9362b15d4806c411a',
    messagingSenderId: '632537420527',
    projectId: 'login-a8323',
    databaseURL: 'https://login-a8323-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'login-a8323.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBziOe3J_ZcLvRcqBunGyQ-6D4FXT7E1tg',
    appId: '1:632537420527:web:ed6a0d7ffdd8f0626c411a',
    messagingSenderId: '632537420527',
    projectId: 'login-a8323',
    authDomain: 'login-a8323.firebaseapp.com',
    databaseURL: 'https://login-a8323-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'login-a8323.appspot.com',
    measurementId: 'G-FYD4M0BYYS',
  );
}
